apiVersion: v1
data:
  script.sh: |-
    !#/bin/bash
    psql $DB_URL << EOF
      CREATE TABLE "public"."senders" (
        "id" bigserial NOT NULL,
        "name" text NOT NULL,
        PRIMARY KEY ("id"),
        UNIQUE("id")
      );

      CREATE TABLE "public"."messages" (
        id bigserial NOT NULL,
        timestamp timestamptz NOT NULL DEFAULT now(),
        message text NOT NULL,
        ip inet,
        priority integer,
        sender_id integer,
        PRIMARY KEY ("id"),
        FOREIGN KEY("sender_id") REFERENCES "public"."senders" ("id") ON UPDATE RESTRICT ON DELETE CASCADE,
        UNIQUE("id")
      );

    EOF
kind: ConfigMap
metadata:
  name: script-configmap
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: seed
  name: seed
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - command:
            - sh
            - /scripts/script.sh
          image: 'bitnami/postgresql'
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-connection-url
                  key: url
          name: script
          volumeMounts:
            - name: script-configmap
              mountPath: /scripts
              readOnly: false
      restartPolicy: Never
      volumes:
        - name: script-configmap
          configMap:
            name: script-configmap
            defaultMode: 0777
