apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: eduardosanzb/producer-ts
          env:
            - name: NODE_ENV
              value: production
            - name: PATH_TO_INSERT_INTO_QUEUE
              value: /to-queue
            - name: POSTGRES_PASSWORD
              value: "8080"
            - name: BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: message-broker
                  key: url
            - name: CHANNEL_NAME
              valueFrom:
                secretKeyRef:
                  name: message-broker
                  key: queue-name
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
